### ISSUE TITLE
unique attribute not working properly

### ISSUE THREAD

**Issue by kristiandelay** [aronluigi/sails-cbes#5]
I have marked the email field attribute to be unique. snippet below:

```
attributes: {
    firstName: 'string',
    email: {
        type: 'string',
        unique: true
    },
    lastName: 'string',
    avatar: 'binary',
    fullName: function() {
        return this.firstName + ' ' + this.lastName;
    }
},
```

when trying to add a new user with the same email i receive the following error: 

Error (E_UNKNOWN) :: Encountered an unexpected error
: DocumentAlreadyExistsException[[index][3] [userTable][userTable:6]: document already exists]
    at respond (/Users/****_/**_**/testProject/node_modules/sails-cbes/node_modules/elasticsearch/src/lib/transport.js:232:15)
    at checkRespForFailure (/Users/****_/**_**/testProject/node_modules/sails-cbes/node_modules/elasticsearch/src/lib/transport.js:200:7)
    at HttpConnector.<anonymous> (/Users/****_/**_**/testProject/node_modules/sails-cbes/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/Users/****_/**_**/testProject/node_modules/sails-cbes/node_modules/lodash/index.js:3128:19)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)

Details:  Error: DocumentAlreadyExistsException[[index][3] [userTable][userTable:6]: document already exists]

This is what i would expect to happen, but the record is still being added to couch.

my UserController code for create:
    create: function(req, res) {
        var params = req.params.all()
        console.log(params);
        if (params.name && params.email) {
            User.create({
                firstName: params.name,
                email: params.email,
            }, function(err, result) {
                if (err) {
                    console.log(err);
                     return res.json(err);
                }

```
            return res.json({
                notice: 'Created user ' + JSON.stringify(result)
            });

        })
    } else {
        return res.json({
            error: 'invalid parameters'
        });
    }

},
```

Is it up to me to remove the duplicated entry if the DocumentAlreadyExistsException is raised, or is this a bug? Any help here would be much appreciated thanks for your time in advanced.

**Comment by aronluigi** [comment]
Hi,

Can you please share the entire model file ?
I can tell you for now that I don't see no mapping. Please have a look at
our documentation.

https://www.npmjs.com/package/sails-cbes

Best regards!
Luigi

Example model:

module.exports = {
    connection: 'sailsCbes',

```
attributes: {
    firstName: 'string',
    lastName: 'string',
    email: {
        type: 'string',
        defaultsTo: 'e@test.com'
    },
    avatar: 'binary',
    title: 'string',
    phone: 'string',
    type: 'string',
    favoriteFruit: {
        defaultsTo: 'blueberry',
        type: 'string'
    },
    age: 'integer', // integer field that's not auto-incrementable
    dob: 'datetime',
    status: {
        type: 'boolean',
        defaultsTo: false
    },
    percent: 'float',
    list: 'array',
    obj: 'json',
    fullName: function () {
        return this.firstName + ' ' + this.lastName;
    }
},

mapping: {
    "_all": {
        "enabled": false
    },
    firstName: {
        type: 'string',
        analyzer: 'whitespace',
        fields: {
            raw: {
                type: 'string',
                index: 'not_analyzed'
            }
        }
    },
    lastName: {
        type: 'string',
        analyzer: 'whitespace'
    },
    email: {
        type: 'string',
        analyzer: 'standard'
    },
    avatar: {
        type: 'binary'
    },
    title: {
        type: 'string',
        analyzer: 'whitespace',
    },
    phone: {
        type: 'string',
        analyzer: 'keyword'
    },
    type: {
        type: 'string',
        analyzer: 'keyword'
    },
    favoriteFruit: {
        type: 'string',
        analyzer: 'whitespace'
    },
    age: {
        type: 'integer',
        index: 'not_analyzed'
    },
    createdAt: {
        type: 'date',
        format: 'dateOptionalTime'
    },
    updatedAt: {
        type: 'date',
        format: 'dateOptionalTime'
    },
    status: {
        type: 'boolean'
    },
    percent: {
        type: 'float'
    },
    obj: {
        type: 'object'
    }
}
```

};

Configuration https://www.npmjs.com/package/sails-cbes#configuration

{
    //couchbase
    cb: {
        host: 'localhost',
        port: 8091,
        user: 'user',
        version: '3.0.3',
        pass: 'password',
        operationTimeout: 60 \* 1000, // 60s

```
    bucket: {
        name: 'bucket',
        pass: 'bucketPassword'
    }
},

//elasticsearch
es: {
    host: ['127.0.0.1:9200'],
    log: 'error',
    index: 'index',
    numberOfShards: 5,
    requestTimeout: 30000,
    numberOfReplicas: 1
}
```

},

**Comment by kristiandelay** [comment]
Here is my entire model: @aronluigi aronluigi
i must have changed something in here to make the DocumentAlreadyExistsException go away but now it just allows me to keep adding the same record 

module.exports = {

```
tableName: 'userTable',
connection: 'sailsCbes',

attributes: {
    firstName: 'string',
    email: {
        type: 'string',
        unique: true
    },
    lastName: 'string',
    avatar: 'binary',
    fullName: function() {
        return this.firstName + ' ' + this.lastName;
    }
},

mapping: {
    "_all": {
        "enabled": false
    },
    firstName: {
        type: 'string',
        analyzer: 'whitespace',
        fields: {
            raw: {
                type: 'string',
                index: 'not_analyzed'
            }
        }
    },
    lastName: {
        type: 'string',
        analyzer: 'whitespace'
    },
    email: {
        type: 'string',
        defaultsTo: 'e@test.com'
    },
    avatar: {
        type: 'binary'
    }
}
```

};

**Comment by aronluigi** [comment]
Hi,

Please remove the line "tableName: 'userTable',", delete your index from
elastic search and flush couchbase bucket. After that try again.
It looks like you already have the document in couchbase or elastic search .

Let me know if it worked

Best regards!
Luigi

**Comment by kristiandelay** [comment]
i blew away both couchbase and elasticsearch and rebuilt them, removed userTable as well. Still the results are the same, multiple records are being added even though being marked unique.

heres some info about versions: 

couchbase

```
Version: 4.0.0-4051 Community Edition (build-4051)
Cluster State ID: 04A-010-127
```

elasticsearch

```
{
"status": 200,
"name": "elasticsearch1",
"cluster_name": "SpottedAt",
"version": {
"number": "1.7.3",
"build_hash": "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
"build_timestamp": "2015-10-15T09:14:17Z",
"build_snapshot": false,
"lucene_version": "4.10.4"
},
"tagline": "You Know, for Search"
}  
```

Im also having lookup issues as well maybe this could help figure out whats going on. 
Below code returns an array of blank objects, I have also tried just using the model from the documents with the same results

```
  var elasticsearchFilterQuery = {
      bool: {
          must: [{
              term: {
                  _TYPE: 'user'
              }
          }, {
              terms: {
                  firstName: ['kristian', 'createEach_2']
              }
          }]
      }
  };

  User.find()
      .where(elasticsearchFilterQuery)
      .exec(function(err, results) {
          if (err) {
              console.log(err);
              return res.json(err);
          }
          return res.json({
              results: results
          });
      });
```

// This is the result thats passed back

```
  {
      results: [{}, {}]
  }
```

Below returns all the results from the user documents correctly.

```
 User.find()
      .exec(function(err, results) {
          if (err) {
              console.log(err);
              return res.json(err);
          }
          // console.log(results);

          return res.json({
              results: results
          });
      });
```

results:

```
results: [{
    firstName: "kristian",
    email: "kristian@gmail.com",
    favoriteFruit: "blueberry",
    status: false,
    createdAt: "2015-10-27T17:20:37.333Z",
    updatedAt: "2015-10-27T17:20:37.333Z",
    id: 0,
    _TYPE: "user"
}, {
    firstName: "kristian",
    email: "kristian@gmail.com",
    favoriteFruit: "blueberry",
    status: false,
    createdAt: "2015-10-27T17:21:05.919Z",
    updatedAt: "2015-10-27T17:21:05.919Z",
    id: 1,
    _TYPE: "user"
}]
}
```

**Comment by aronluigi** [comment]
Hi,

Sorry, I understood wrong the problem. At the moment the adapter doesn't support unique = true.

The workaround for this is:
Before adding a new user search if you already have a user with that email.

If the result is bigger than 0 you don't create the new one.

Also, you are welcome to help us improve the adaptor to fit your needs.

Best regards!
Luigi

**Comment by aronluigi** [comment]
Hi,

Good news! the problem is fixed. Please update, give it a try and let me know.

Model example:

attributes: {
        firstName: 'string',
        lastName: {
            type: 'string',
            unique: true
        },
        email: {
            type: 'string',
            defaultsTo: 'e@test.com',
            unique: true
        }
    },

```
mapping: {
    "_all": {
        "enabled": false
    },
    firstName: {
        type: 'string',
        analyzer: 'whitespace',
        fields: {
            raw: {
                type: 'string',
                index: 'not_analyzed'
            }
        }
    },
    lastName: {
        type: 'string',
        analyzer: 'whitespace'
    },
    email: {
        type: 'string',
        analyzer: 'keyword'
    }
}
```
