### ISSUE TITLE
Init with couchbase only

### ISSUE THREAD

**Issue by fed135** [aronluigi/sails-cbes#7]
I'm trying to use the adapter to connect to Couchbase only - we don't have ElasticSearch set-up.
I've made a fork and tried wrapping the `self._initElasticSearch` statement in a condition that checks if the `es` property of the config isn't false. In which case I invoke the callback.

Traced the process, it triggers the callback in `registerConnection`, but then I get this message:

```
Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback (...)
E_HOOK_TIMEOUT
```

Never fiddled in sails adapters, anything I should be looking for ?
Thanks!

**Comment by aronluigi** [comment]
I you want to use only couchbase you need to change almost all the functions (create, update, delete, find ....).

About the error it looks like you missed a callback or return some ware.

**Comment by fed135** [comment]
Yeah I noticed after I opened the ticket. We'll be using a different solution. Thank you
